version: '3'
services:
  node-app: #image_name 
    build: .
    depends_on:
      - mongodb
    deploy:
      replicas: 5
    ports:
      - 3000-3006:3000
    volumes:
      - ./:/app:ro  ## bind mounts help to synchronize
      - /app/node_modules ## anonymous volumes
    env_file:
      - ./.env
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=owais
      - MONGO_INITDB_ROOT_PASSWORD=owais
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: